export const clinicConfig = {
  doctors: [
    "Dr. Ashwani Kumar"
  ],
  procedures: [
    "General Cosmetic Consultation",
    "Facial Aesthetic Consultation",
    "Gynecomastia Surgery (Male Breast Reduction)",
    "Puffy Nipple Surgery",
    "VASER 4D Liposuction (High-Definition Body Sculpting)",
    "Abdominoplasty (Tummy Tuck)",
    "Six Pack Abs Creation",
    "Mommy Makeover",
    "Rhinoplasty (Nose Reshaping)",
    "Blepharoplasty (Eyelid Surgery)",
    "Facelift (Rhytidectomy)",
    "Buccal Fat Pad Removal",
    "Lip Reduction",
    "Chin Implant / Augmentation",
    "Breast Augmentation (Implants)",
    "Breast Reduction Surgery",
    "Breast Lift (Mastopexy)",
    "Saggy Arms Surgery (Brachioplasty)",
    "Head Hair Transplant (FUE)",
    "Beard & Moustache Hair Transplant",
    "Eyebrow Hair Transplant",
    "PRP Hair Loss Therapy",
    "Mesotherapy for Hair",
    "Sex Reassignment Surgery (Gender Affirmation)",
    "Botox and Dermal Fillers",
    "Chemical Peels",
    "Laser Hair Removal",
    "Scarless Lipoma Removal",
    "Scar Remodeling / Revision",
    "Mole & Skin Tag Removal",
    "Hymenoplasty",
    "Labiaplasty Surgery",
    "Vaginal Tightening",
    "Other"
  ]
};
